# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suggest_faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='suggest_faq.Tables'),
        ),
    ]
