# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suggest_faq', '0003_auto_20160709_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggest_faq', to='suggest_faq.SuperUsers'),
        ),
    ]
